### ISSUE TITLE
Run all code when none selected

### ISSUE THREAD

**Issue by texastoland** [statiolake/vscode-markdown-run-snippet#2]
If no code is selected, all code blocks in the file should be ran as the first language.

**Comment by statiolake** [comment]
Thanks for using the extension.

Currently I have no idea to run multiple snippets.

I tried to implement it, but it seems code-runner extension only supports running one code at the same time. Also, I cannot find the way to get whether a code is running or not from outside of the code-runner extension ("running or not" is managed by a private flag variable in that extension and the variable is not exposed to the outside), it is difficult to run them one by one by waiting for finish of the running of the previous code snippet.
